#spring.application.name=spring-IMS

spring:
  application:
    name: springboot-helloworld
  thymeleaf.cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zz0426

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
#    email sender info
    username: zinkxywork@gmail.com 
    password: fugw otkx gbdo ulun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true